import { Capacitor, registerPlugin } from '@capacitor/core';
import { Share } from '@capacitor/share';

export const isNative = () => Capacitor.isNativePlatform();
export const publicAppUrl = 'https://app.commandeici.com';
export const authRedirectUrl = (path: string) => isNative() ? `commandeici://auth${path}` : `${window.location.origin}${path}`;

export function nativeRoute(input: string): string | null {
  try {
    const url = new URL(input);
    const callbackPaths = ['/inscription', '/profil', '/order', '/connexion', '/reinitialiser-mot-de-passe'];
    if (url.username || url.password || (url.port && url.port !== '443')) return null;
    if (url.protocol === 'commandeici:' && url.hostname === 'auth') {
      if (!callbackPaths.includes(url.pathname)) return null;
    } else if (url.protocol !== 'https:' || url.hostname !== 'app.commandeici.com') return null;
    if (!url.pathname.startsWith('/') || url.pathname.startsWith('//')) return null;
    const fragment = new URLSearchParams(url.hash.slice(1));
    // Native auth uses PKCE. Supplied bearer tokens must never replace its session.
    if (['access_token', 'refresh_token'].some(key => fragment.has(key) || url.searchParams.has(key))) return null;
    if (url.searchParams.has('code') && (!callbackPaths.includes(url.pathname) || !url.searchParams.get('code') || url.searchParams.getAll('code').length !== 1)) return null;
    return url.pathname + url.search + url.hash;
  } catch { return null; }
}

interface SecureSessionPlugin {
  get(options: { key: string }): Promise<{ value: string | null }>;
  set(options: { key: string; value: string }): Promise<void>;
  remove(options: { key: string }): Promise<void>;
}
const secureSession = registerPlugin<SecureSessionPlugin>('SecureSession');
export const nativeSessionStorage = {
  getItem: async (key: string) => (await secureSession.get({ key })).value,
  setItem: async (key: string, value: string) => { await secureSession.set({ key, value }); },
  removeItem: async (key: string) => { await secureSession.remove({ key }); },
};

export async function shareRestaurant(slug: string, title: string) {
  const url = `${publicAppUrl}/${encodeURIComponent(slug)}`;
  if (isNative()) await Share.share({ title, url });
  else if (navigator.share) await navigator.share({ title, url });
  else await navigator.clipboard.writeText(url);
}

interface FileExportPlugin {
  openNotificationSettings(): Promise<void>;
  openExternalUrl(options: { url: string }): Promise<void>;
  share(options: { base64: string; filename: string; mimeType: string }): Promise<{ completed: boolean }>;
}
const fileExport = registerPlugin<FileExportPlugin>('FileExport');

// WKWebView does not provide browser download handling. Export the actual
// generated bytes through the iOS share sheet, including Save to Files.
export async function exportPublicFile(data: string, filename: string, mimeType: string): Promise<boolean> {
  const extensions: Record<string, string> = { 'image/png': '.png', 'image/svg+xml': '.svg', 'application/pdf': '.pdf' };
  if (!extensions[mimeType] || !/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,199}$/.test(filename) || !filename.endsWith(extensions[mimeType])) {
    throw new Error('Invalid export file');
  }
  let base64: string;
  if (data.startsWith('data:')) {
    const comma = data.indexOf(',');
    const header = data.slice(0, comma);
    if (comma === -1 || !header.startsWith(`data:${mimeType};`) || !header.endsWith(';base64')) throw new Error('Invalid export data');
    base64 = data.slice(comma + 1);
  } else {
    if (mimeType !== 'image/svg+xml') throw new Error('Invalid export data');
    const bytes = new TextEncoder().encode(data);
    let binary = '';
    for (let offset = 0; offset < bytes.length; offset += 32768) {
      binary += String.fromCharCode(...bytes.subarray(offset, offset + 32768));
    }
    base64 = btoa(binary);
  }
  if (!base64 || base64.length > 28 * 1024 * 1024 || !/^[A-Za-z0-9+/]+={0,2}$/.test(base64)) throw new Error('Invalid export data');
  if (isNative()) return (await fileExport.share({ base64, filename, mimeType })).completed;
  const link = document.createElement('a');
  link.download = filename;
  link.href = `data:${mimeType};base64,${base64}`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  return true;
}

// OAuth providers require a real browser, rather than the app WKWebView.
export async function openExternalUrl(input: string): Promise<void> {
  const url = new URL(input);
  if (url.protocol !== 'https:' || !url.hostname || url.username || url.password || (url.port && url.port !== '443')) {
    throw new Error('Invalid external URL');
  }
  if (isNative()) await fileExport.openExternalUrl({ url: url.href });
  else window.location.assign(url.href);
}

export async function openNotificationSettings(): Promise<void> {
  if (isNative()) await fileExport.openNotificationSettings();
}
