import {useEffect,useState} from 'react';
import {Link,Navigate,useParams,useSearchParams} from 'react-router-dom';
import {ArrowLeft,Check,Minus,Plus,ShoppingBag} from 'lucide-react';
import {BrandLogo} from '@/components/BrandLogo';
import {LanguageSelector} from '@/components/restaurant/LanguageSelector';
import {Button} from '@/components/ui/button';
import {Sheet,SheetContent,SheetHeader,SheetTitle} from '@/components/ui/sheet';
import {useLanguage} from '@/context/LanguageContext';
import {matchesMenuSearch} from '@/lib/menu-search';
import {advanceCommerceDemoOrder,commerceDemoTotal,createCommerceDemoOrder,demoCatalog,loadCommerceDemo,saveCommerceDemo,type DemoSector,type DemoProduct} from '@/lib/demo-commerce';
const steps=['new','preparing','ready','done'] as const;
function CommerceDemo({sector}:{sector:DemoSector}){
 const {t}=useLanguage();const [params,setParams]=useSearchParams();const catalog=demoCatalog(sector);
 const [state,setState]=useState(()=>loadCommerceDemo(sector));const [query,setQuery]=useState('');const [category,setCategory]=useState('');const [basketOpen,setBasketOpen]=useState(false);const [announcement,setAnnouncement]=useState('');
 const merchant=params.get('vue')==='commercant';
 const setView=(view:'client'|'commercant')=>setParams(current=>{const next=new URLSearchParams(current);next.set('vue',view);return next;},{replace:true});
 useEffect(()=>saveCommerceDemo(sector,state),[sector,state]);
 const count=Object.values(state.cart).reduce((sum,quantity)=>sum+quantity,0);const total=commerceDemoTotal(sector,state.cart);const latest=state.orders[0];const progress=latest?steps.indexOf(latest.status)+1:0;
 const categories=[...new Set(catalog.products.map(product=>product.categoryKey))];
 const visible=catalog.products.filter(product=>(!category||category===product.categoryKey)&&matchesMenuSearch(query,{name:t(product.nameKey),category:t(product.categoryKey)}));
 const change=(product:DemoProduct,delta:number)=>{
  setState(current=>{const cart={...current.cart};const quantity=Math.min(99,(cart[product.id]??0)+delta);if(quantity<=0)delete cart[product.id];else cart[product.id]=quantity;return {...current,cart};});
  if(delta>0)setAnnouncement(t('commerce.added',{product:t(product.nameKey)}));
 };
 const simulate=()=>{
  setState(current=>{if(!Object.keys(current.cart).length)return current;const number=1+Math.max(0,...current.orders.map(order=>order.number));const order=createCommerceDemoOrder(sector,current.cart,number);return {cart:{},orders:[order,...current.orders].slice(0,20)};});
  setBasketOpen(false);setView('commercant');setAnnouncement(t('commerce.received_help'));window.scrollTo({top:0});
 };
 const sample=()=>setState(current=>{const number=1+Math.max(0,...current.orders.map(order=>order.number));return {...current,orders:[createCommerceDemoOrder(sector,{[catalog.products[0].id]:1},number),...current.orders].slice(0,20)};});
 return <div className="min-h-screen bg-white pb-28"><header className="border-b border-slate-100"><div className="mx-auto max-w-3xl px-4 min-h-16 flex items-center justify-between gap-3"><Link to="/decouvrir" aria-label="commandeici"><BrandLogo/></Link><LanguageSelector/></div></header>
 <main className="mx-auto max-w-3xl px-4 py-4 sm:py-6"><Link to="/decouvrir" className="inline-flex min-h-11 items-center gap-2 text-sm text-slate-600"><ArrowLeft className="h-4 w-4 rtl:rotate-180" aria-hidden="true"/>{t('commerce.change_demo')}</Link>
 <div className="relative mt-3 overflow-hidden rounded-3xl bg-[#f7f4ee]"><img src={catalog.hero} alt="" width="640" height="640" loading="eager" className="h-44 w-full object-cover sm:h-56"/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/75 to-transparent px-5 pb-4 pt-10"><h1 className="text-2xl font-bold text-white">{t(catalog.nameKey)}</h1><p className="mt-1 text-sm text-white/90">{t('commerce.demo_short')}</p></div></div>
 <p className="mt-3 text-xs leading-relaxed text-slate-500">{t('commerce.demo_note')}</p>
 <div role="group" aria-label={t('commerce.view')} className="mt-5 flex rounded-xl bg-slate-100 p-1">{(['client','commercant'] as const).map(view=><button key={view} type="button" id={'view-'+view} aria-controls={'panel-'+view} aria-pressed={merchant===(view==='commercant')} className={`flex-1 min-h-11 rounded-lg px-3 text-sm font-semibold ${merchant===(view==='commercant')?'bg-white text-primary shadow-sm':'text-slate-600'}`} onClick={()=>setView(view)}>{t(view==='client'?'commerce.client':'commerce.merchant')}</button>)}</div>
 <p role="status" aria-live="polite" className="sr-only">{announcement}</p>
 {!merchant?<section role="region" id="panel-client" aria-labelledby="view-client" className="mt-5">
  <div className="flex items-center gap-2 rounded-xl border border-slate-200 px-3"><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('commerce.search')} aria-label={t('commerce.search')} className="flex-1 min-w-0 py-3 text-base outline-none [&::-webkit-search-cancel-button]:hidden"/>{query&&<button className="min-h-11 px-2 text-sm text-primary" onClick={()=>setQuery('')}>{t('journey.clear_search')}</button>}</div>
  <div className="my-4 flex gap-2 overflow-x-auto pb-1"><button onClick={()=>setCategory('')} aria-pressed={!category} className={`min-h-11 shrink-0 rounded-full px-4 text-sm ${!category?'bg-primary text-white':'bg-slate-100 text-slate-700'}`}>{t('commerce.all')}</button>{categories.map(key=><button key={key} onClick={()=>setCategory(key)} aria-pressed={category===key} className={`min-h-11 shrink-0 rounded-full px-4 text-sm ${category===key?'bg-primary text-white':'bg-slate-100 text-slate-700'}`}>{t(key)}</button>)}</div>
  {visible.length===0&&<p role="status" className="py-6 text-sm text-slate-600">{t('commerce.no_results')}</p>}
  <div className="grid grid-cols-2 gap-3">{visible.map(product=><article key={product.id} className="min-w-0 overflow-hidden rounded-2xl border border-slate-200"><div className="relative bg-[#f7f4ee]"><img src={product.image} alt={t(product.nameKey)} width="320" height="320" loading="lazy" className={`aspect-square w-full ${product.categoryKey==='commerce.drinks'?'object-contain p-4':'object-cover'}`}/><span className="absolute bottom-0 inset-x-0 bg-black/45 px-2 text-center text-[9px] leading-4 text-white">{t('menu.illustration')}</span></div><div className="p-3"><h2 className="min-h-10 text-sm font-semibold leading-snug text-slate-900">{t(product.nameKey)}</h2><p className="mt-1 text-sm font-bold text-slate-900">{product.price.toFixed(2)} €</p><button className="mt-3 flex flex-wrap w-full min-h-11 items-center justify-center gap-1 rounded-xl bg-primary px-2 py-2 text-sm font-semibold text-white" onClick={()=>change(product,1)} aria-label={t('commerce.add',{product:t(product.nameKey)})}>{t('common.add')}<Plus className="h-4 w-4 shrink-0" aria-hidden="true"/></button></div></article>)}</div>
 </section>:<section role="region" id="panel-commercant" aria-labelledby="view-commercant" className="mt-5">
  <h2 className="text-lg font-semibold text-slate-900">{t('commerce.orders')}</h2><p className="mt-2 text-sm text-slate-600">{t('commerce.received_help')}</p>
  <div role="progressbar" aria-label={t('commerce.orders')} aria-valuemin={0} aria-valuemax={4} aria-valuenow={progress} className="my-4 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-primary transition-[width] motion-reduce:transition-none" style={{width:`${progress*25}%`}}/></div>
  <ol className="grid grid-cols-4 gap-2 text-[11px] text-slate-600">{steps.map((step,index)=><li key={step} aria-current={progress===index+1?'step':undefined} className={index<progress?'text-primary':'text-slate-500'}>{t('dashboard.orders.status_'+step)}</li>)}</ol>
  <Button onClick={sample} variant="outline" className="my-4 min-h-11 h-auto whitespace-normal py-3">{t('demo.try.receive')}</Button>
  {!state.orders.length&&<p className="text-sm text-slate-500">{t('commerce.empty_orders')}</p>}
  <div className="space-y-3">{state.orders.map(order=><article key={order.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold text-slate-900">{t('commerce.order_number',{number:order.number})}</h3><span className="text-xs font-medium text-primary">{t('dashboard.orders.status_'+order.status)}</span></div><ul className="mt-3 space-y-2 text-sm text-slate-600">{catalog.products.filter(product=>order.items[product.id]).map(product=><li key={product.id} className="flex items-center gap-3"><img src={product.image} alt="" width="40" height="40" className="h-10 w-10 shrink-0 rounded-lg object-cover"/><span>{order.items[product.id]} × {t(product.nameKey)}</span></li>)}</ul><p className="mt-3 font-semibold">{order.total.toFixed(2)} €</p>{order.status!=='done'?<Button className="mt-3 min-h-11 h-auto whitespace-normal py-3" onClick={()=>setState(current=>({...current,orders:current.orders.map(existing=>existing.id===order.id?advanceCommerceDemoOrder(existing):existing)}))}>{t(order.status==='new'?'commerce.prepare':order.status==='preparing'?'commerce.ready':'commerce.collected')}</Button>:<p className="mt-3 flex items-center gap-2 text-sm text-primary"><Check className="h-4 w-4" aria-hidden="true"/>{t('commerce.collected')}</p>}</article>)}</div>
  {progress===4&&<Link to="/inscription" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-white">{t('home.create_free')}</Link>}
 </section>}
 </main>
 {!merchant&&count>0&&<div className="fixed inset-x-0 bottom-0 z-40 border-t border-slate-100 bg-white/95 px-4 pt-3" style={{paddingBottom:'max(0.75rem, env(safe-area-inset-bottom))'}}><Button className="mx-auto flex w-full max-w-3xl min-h-12 h-auto whitespace-normal justify-between gap-3 rounded-xl py-3" onClick={()=>setBasketOpen(true)}><span className="inline-flex items-center gap-2"><ShoppingBag className="h-4 w-4 shrink-0" aria-hidden="true"/>{t('commerce.basket',{count})}</span><span>{total.toFixed(2)} €</span></Button></div>}
 <Sheet open={basketOpen} onOpenChange={setBasketOpen}><SheetContent className="flex w-full flex-col p-0 sm:max-w-md [&>button]:min-h-11 [&>button]:min-w-11 [&>button]:top-[calc(1rem+env(safe-area-inset-top,0px))]" style={{paddingTop:'env(safe-area-inset-top,0px)',paddingBottom:'env(safe-area-inset-bottom,0px)'}}><SheetHeader className="border-b border-slate-100 p-4"><SheetTitle>{t('cart.your_cart')}</SheetTitle></SheetHeader><div className="flex-1 min-h-0 space-y-3 overflow-y-auto p-4">{catalog.products.filter(product=>state.cart[product.id]).map(product=><div key={product.id} className="rounded-xl border border-slate-200 p-3"><div className="flex items-center gap-3"><img src={product.image} alt="" width="56" height="56" className="h-14 w-14 shrink-0 rounded-lg object-cover"/><div className="min-w-0"><p className="text-sm font-semibold">{t(product.nameKey)}</p><p className="mt-1 text-sm">{(state.cart[product.id]*product.price).toFixed(2)} €</p></div></div><div className="mt-2 flex items-center justify-end gap-3"><button className="flex min-h-11 min-w-11 items-center justify-center rounded-full bg-slate-100" onClick={()=>change(product,-1)} aria-label={t('commerce.decrease',{product:t(product.nameKey)})}><Minus className="h-4 w-4"/></button><span className="text-sm font-semibold">{state.cart[product.id]}</span><button className="flex min-h-11 min-w-11 items-center justify-center rounded-full bg-slate-100" onClick={()=>change(product,1)} aria-label={t('commerce.increase',{product:t(product.nameKey)})}><Plus className="h-4 w-4"/></button></div></div>)}</div><div className="border-t border-slate-100 p-4"><p className="mb-3 text-xs leading-relaxed text-slate-500">{t('commerce.demo_note')}</p><Button disabled={!count} className="w-full min-h-12 h-auto whitespace-normal rounded-xl py-3" onClick={simulate}>{t('commerce.simulate')}</Button></div></SheetContent></Sheet>
 </div>;
}
export default function CommerceDemoPage(){const {sector}=useParams();return sector==='epicerie'||sector==='fleuriste'?<CommerceDemo key={sector} sector={sector}/>:<Navigate to="/decouvrir" replace/>;}
