import {useEffect,useRef,useState} from 'react';
import {Link,Navigate,useParams,useSearchParams} from 'react-router-dom';
import {ArrowLeft,Check,Plus,ShoppingBag,Store} from 'lucide-react';
import {BrandLogo} from '@/components/BrandLogo';
import {LanguageSelector} from '@/components/restaurant/LanguageSelector';
import {Button} from '@/components/ui/button';
import {useLanguage} from '@/context/LanguageContext';
import {matchesMenuSearch} from '@/lib/menu-search';
import {CommerceProductSheet} from '@/components/commerce/CommerceProductSheet';
import {CommerceBasketSheet} from '@/components/commerce/CommerceBasketSheet';
import {CommerceMerchant} from '@/components/commerce/CommerceMerchant';
import {CommerceOrderCard} from '@/components/commerce/CommerceOrderCard';
import {advanceCommerceDemoOrder,addCommerceDemoLine,changeCommerceDemoQuantity,collectCommerceDemoOrder,commerceDemoTotal,demoCatalog,loadCommerceDemo,receiveCommerceDemoSample,saveCommerceDemo,submitCommerceDemoOrder,updateCommerceDemoProduct,type CommerceDemoState,type DemoSector,type DemoProduct} from '@/lib/demo-commerce';
const steps=['new','preparing','ready','done'] as const;
function CommerceDemo({sector}:{sector:DemoSector}) {
 const {t,language}=useLanguage();const [params,setParams]=useSearchParams();const catalog=demoCatalog(sector);
 const [state,setState]=useState(()=>loadCommerceDemo(sector));const current=useRef(state);
 const [query,setQuery]=useState('');const [category,setCategory]=useState('');const [basketOpen,setBasketOpen]=useState(false);const [product,setProduct]=useState<DemoProduct|null>(null);const [announcement,setAnnouncement]=useState('');const [error,setError]=useState('');
 const productFocus=useRef<HTMLElement|null>(null);const basketFocus=useRef<HTMLElement|null>(null);
 const merchant=params.get('vue')==='commercant';
 const setView=(view:'client'|'commercant')=>{setParams(previous=>{const next=new URLSearchParams(previous);next.set('vue',view);return next;},{replace:true});setError('');};
 useEffect(()=>saveCommerceDemo(sector,state),[sector,state]);
 const mutate=(update:(value:CommerceDemoState)=>CommerceDemoState)=>{
  try {const next=update(current.current);current.current=next;setState(next);setError('');return true;}
  catch(reason) {const key=reason instanceof Error&&['commerce.unavailable','commerce.invalid_value','commerce.adjust_basket'].includes(reason.message)?reason.message:'commerce.demo_error';setError(t(key));return false;}
 };
 const count=state.cart.reduce((sum,line)=>sum+line.quantity,0);const total=commerceDemoTotal(sector,state.cart);const latest=state.orders[0];const progress=latest?steps.indexOf(latest.status)+1:0;
 const price=(amount:number)=>new Intl.NumberFormat(language,{style:'currency',currency:'EUR'}).format(amount);
 const categories=[...new Set(catalog.products.map(item=>item.categoryKey))];
 const visible=catalog.products.filter(item=>state.products[item.id].enabled&&(!category||category===item.categoryKey)&&matchesMenuSearch(query,{name:t(item.nameKey),category:t(item.categoryKey)}));
 const simulate=()=>{if(!current.current.cart.length)return;if(mutate(value=>submitCommerceDemoOrder(sector,value,value.pickup))){setBasketOpen(false);setView('commercant');setAnnouncement(t('commerce.received_help'));window.scrollTo({top:0});}};
 const advance=(id:string)=>mutate(value=>({...value,orders:value.orders.map(order=>order.id===id&&(order.status==='new'||order.status==='preparing')?advanceCommerceDemoOrder(order):order)}));
 return <div className="min-h-screen bg-white pb-28 text-slate-900"><header className="border-b border-slate-100"><div className="mx-auto flex min-h-16 max-w-3xl items-center justify-between gap-3 px-4"><Link to="/decouvrir" aria-label="commandeici"><BrandLogo/></Link><LanguageSelector/></div></header>
  <main className="mx-auto max-w-3xl break-words px-4 py-4 sm:py-6"><Link to="/decouvrir" className="inline-flex min-h-11 items-center gap-2 text-sm text-slate-600"><ArrowLeft className="h-4 w-4 rtl:rotate-180" aria-hidden="true"/>{t('commerce.change_demo')}</Link>
   <div className={`relative mt-3 overflow-hidden rounded-3xl bg-[#f7f4ee] ${merchant?'sm:flex sm:items-center':''}`}><img src={catalog.hero} alt="" width="640" height="640" loading="eager" className={`w-full object-cover ${merchant?'h-32 sm:h-36 sm:w-48':'h-36 sm:h-48'}`}/><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/75 to-transparent px-5 pb-4 pt-10"><h1 className="text-2xl font-bold text-white">{t(catalog.nameKey)}</h1><p className="mt-1 text-sm text-white/90">{t('commerce.demo_short')}</p></div></div>
   <p className="mt-3 flex items-center gap-2 text-sm font-medium text-primary"><Store className="h-4 w-4 shrink-0" aria-hidden="true"/>{t('commerce.collect_in_shop')}</p>{merchant&&<p className="mt-2 text-xs leading-relaxed text-slate-500">{t('commerce.demo_note')}</p>}
   <div role="group" aria-label={t('commerce.view')} className="mt-5 flex rounded-xl bg-slate-100 p-1">{(['client','commercant'] as const).map(view=><button key={view} type="button" id={'view-'+view} aria-controls={'panel-'+view} aria-pressed={merchant===(view==='commercant')} className={`min-h-11 flex-1 rounded-lg px-3 py-2 text-sm font-semibold ${merchant===(view==='commercant')?'bg-white text-primary shadow-sm':'text-slate-600'}`} onClick={()=>setView(view)}>{t(view==='client'?'commerce.client':'commerce.merchant')}</button>)}</div>
   <p role="status" aria-live="polite" className="sr-only">{announcement}</p>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
   {latest&&<section aria-label={t('commerce.follow_order')} className="mt-5 rounded-2xl border border-primary/20 bg-primary/5 p-4"><div className="flex items-center justify-between gap-2"><h2 className="text-sm font-semibold">{t('commerce.my_order')}</h2><span className="text-xs font-semibold text-primary">{t('commerce.order_number',{number:latest.number})}</span></div><div role="progressbar" aria-label={t('commerce.orders')} aria-valuemin={0} aria-valuemax={4} aria-valuenow={progress} className="my-3 h-1.5 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-primary transition-[width] motion-reduce:transition-none" style={{width:`${progress*25}%`}}/></div><ol className="grid grid-cols-4 gap-2 text-[11px] leading-snug">{steps.map((step,index)=><li key={step} aria-current={index+1===progress?'step':undefined} className={index<progress?'text-primary':'text-slate-500'}>{t('dashboard.orders.status_'+step)}</li>)}</ol><p className="mt-3 text-sm leading-relaxed text-slate-600">{t('commerce.status_'+latest.status+'_help')}</p>{latest.status==='done'&&<Link to="/inscription" className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-white"><Check className="h-4 w-4 shrink-0" aria-hidden="true"/>{t('home.create_free')}</Link>}</section>}
   {!merchant?<section role="region" id="panel-client" aria-labelledby="view-client" className="mt-5">
    <div className="flex items-center gap-2 rounded-xl border border-slate-200 px-3"><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder={t('commerce.search')} aria-label={t('commerce.search')} className="min-w-0 flex-1 py-3 text-base outline-none focus-visible:ring-2 focus-visible:ring-primary [&::-webkit-search-cancel-button]:hidden"/>{query&&<button type="button" className="min-h-11 px-2 text-sm text-primary" onClick={()=>setQuery('')}>{t('journey.clear_search')}</button>}</div>
    <div className="my-4 flex gap-2 overflow-x-auto pb-1"><button type="button" onClick={()=>setCategory('')} aria-pressed={!category} className={`min-h-11 shrink-0 rounded-full px-4 text-sm ${!category?'bg-primary text-white':'bg-slate-100 text-slate-700'}`}>{t('commerce.all')}</button>{categories.map(key=><button type="button" key={key} onClick={()=>setCategory(key)} aria-pressed={category===key} className={`min-h-11 shrink-0 rounded-full px-4 text-sm ${category===key?'bg-primary text-white':'bg-slate-100 text-slate-700'}`}>{t(key)}</button>)}</div>
    {visible.length===0&&<div className="py-6"><p role="status" className="text-sm text-slate-600">{t('commerce.no_results')}</p><Button variant="outline" className="mt-3 min-h-11" onClick={()=>{setQuery('');setCategory('');}}>{t('commerce.all')}</Button></div>}
    <div className="grid grid-cols-2 gap-3">{visible.map(item=>{const value=state.products[item.id];return <article key={item.id} className="min-w-0 overflow-hidden rounded-2xl border border-slate-200"><button type="button" disabled={!value.stock} aria-label={t(item.options.length?'commerce.choose':'commerce.add',{product:t(item.nameKey)})} onClick={event=>{productFocus.current=event.currentTarget;setProduct(item);setError('');}} className="flex h-full w-full flex-col text-start focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary disabled:opacity-60"><div className="relative w-full bg-[#f7f4ee]"><img src={item.image} alt={t(item.nameKey)} width="320" height="320" loading="lazy" className={`aspect-square w-full ${item.categoryKey==='commerce.drinks'?'object-contain p-4':'object-cover'}`}/><span className="absolute bottom-0 inset-x-0 bg-black/45 px-2 text-center text-[9px] leading-4 text-white">{t('menu.illustration')}</span></div><div className="flex w-full flex-1 flex-col p-3"><h2 className="min-h-10 text-sm font-semibold leading-snug">{t(item.nameKey)}</h2><p className="mt-1 text-xs text-slate-500">{t(item.unitKey)}</p><p className="mt-2 text-sm font-bold">{item.options.length?t('commerce.from_price',{price:price(value.priceCents/100)}):price(value.priceCents/100)}</p><span className="mt-3 flex min-h-11 w-full flex-wrap items-center justify-center gap-2 rounded-xl bg-primary px-2 py-2 text-center text-sm font-semibold text-white">{value.stock?(item.options.length?t('commerce.choose_short'):t('common.add')):t('commerce.sold_out')}<Plus className="h-4 w-4 shrink-0" aria-hidden="true"/></span></div></button></article>;})}</div>
    <p className="mt-5 text-xs leading-relaxed text-slate-500">{t('commerce.demo_note')}</p>{latest&&<div className="mt-6"><CommerceOrderCard sector={sector} order={latest}/><Button variant="outline" className="mt-3 h-auto min-h-11 w-full whitespace-normal" onClick={()=>setView('commercant')}>{t('commerce.merchant')}</Button></div>}
   </section>:<section role="region" id="panel-commercant" aria-labelledby="view-commercant" className="mt-5"><CommerceMerchant sector={sector} state={state} onSample={()=>{if(mutate(value=>receiveCommerceDemoSample(sector,value)))setAnnouncement(t('commerce.received_help'));}} onAdvance={advance} onCollect={(id,payment)=>mutate(value=>collectCommerceDemoOrder(value,id,payment))} onUpdate={(id,patch)=>{const success=mutate(value=>updateCommerceDemoProduct(sector,value,id,patch));if(success)setAnnouncement(t('commerce.product_saved'));return success;}}/></section>}
  </main>
  {!merchant&&count>0&&<div className="fixed inset-x-0 bottom-0 z-40 border-t border-slate-100 bg-white/95 px-4 pt-3" style={{paddingBottom:'max(0.75rem, env(safe-area-inset-bottom))'}}><Button className="mx-auto flex h-auto min-h-12 w-full max-w-3xl justify-between gap-3 whitespace-normal rounded-xl py-3" onClick={event=>{basketFocus.current=event.currentTarget;setBasketOpen(true);}}><span className="inline-flex items-center gap-2"><ShoppingBag className="h-4 w-4 shrink-0" aria-hidden="true"/>{t('commerce.basket',{count})}</span><span>{price(total)}</span></Button></div>}
  {product&&<CommerceProductSheet key={product.id} sector={sector} product={product} state={state} onClose={()=>setProduct(null)} onAdd={line=>{const success=mutate(value=>addCommerceDemoLine(sector,value,line));if(success)setAnnouncement(t('commerce.added',{product:t(product.nameKey)}));return success;}} returnFocus={productFocus.current}/>}
  {basketOpen&&<CommerceBasketSheet sector={sector} state={state} onClose={()=>setBasketOpen(false)} onChange={(key,delta)=>mutate(value=>changeCommerceDemoQuantity(sector,value,key,delta))} onPickup={pickup=>mutate(value=>({...value,pickup}))} onSubmit={simulate} returnFocus={basketFocus.current}/>}
 </div>;
}
export default function CommerceDemoPage(){const {sector}=useParams();return sector==='epicerie'||sector==='fleuriste'?<CommerceDemo key={sector} sector={sector}/>:<Navigate to="/decouvrir" replace/>;}
