import {useRef,useState} from 'react';
import {ClipboardList,Package,Wallet} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {useLanguage} from '@/context/LanguageContext';
import {demoCatalog,type DemoSector,type DemoProduct,type CommerceDemoState,type CommerceProductState} from '@/lib/demo-commerce';
import {CommerceProductEdit} from './CommerceProductEdit';
import {CommerceOrderCard} from './CommerceOrderCard';
type Tab='orders'|'catalog'|'cash';
export function CommerceMerchant({sector,state,onSample,onAdvance,onCollect,onUpdate}: {
 sector:DemoSector;state:CommerceDemoState;onSample:()=>void;onAdvance:(id:string)=>void;
 onCollect:(id:string,payment:'cash'|'card')=>void;onUpdate:(id:string,patch:CommerceProductState)=>boolean;
}) {
 const {t,language}=useLanguage();const catalog=demoCatalog(sector);const [tab,setTab]=useState<Tab>('orders');const [editing,setEditing]=useState<DemoProduct|null>(null);const focus=useRef<HTMLElement|null>(null);const [payments,setPayments]=useState<Record<string,'cash'|'card'>>({});
 const ready=state.orders.filter(order=>order.status==='ready');const pending=state.orders.filter(order=>order.status==='new').length;const done=state.orders.filter(order=>order.status==='done');
 const price=(cents:number)=>new Intl.NumberFormat(language,{style:'currency',currency:'EUR'}).format(cents/100);
 return <>
  <div className="my-5 grid grid-cols-3 gap-2 rounded-2xl bg-slate-50 p-3">{[[pending,'commerce.new_count'],[ready.length,'commerce.ready_count'],[done.length,'commerce.collected_count']].map(([value,label])=><div key={label} className="min-w-0"><p className="text-xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs leading-snug text-slate-600">{t(String(label))}</p></div>)}</div>
  {tab==='orders'&&<section id="commerce-orders" aria-labelledby="commerce-tab-orders"><h2 className="text-lg font-semibold">{t('commerce.orders')}</h2><p className="mt-2 text-sm leading-relaxed text-slate-600">{t('commerce.explore_merchant')}</p><Button variant="outline" onClick={onSample} className="my-4 h-auto min-h-11 whitespace-normal py-3">{t('demo.try.receive')}</Button>
   {!state.orders.length&&<p className="mb-4 text-sm text-slate-500">{t('commerce.empty_orders')}</p>}
   <div className="space-y-3">{state.orders.map(order=><CommerceOrderCard key={order.id} sector={sector} order={order}>{order.status!=='done'&&<Button onClick={()=>order.status==='ready'?setTab('cash'):onAdvance(order.id)} className="mt-4 h-auto min-h-11 w-full whitespace-normal py-3">{t(order.status==='new'?'commerce.prepare':order.status==='preparing'?'commerce.ready':'commerce.nav_cash')}</Button>}</CommerceOrderCard>)}</div>
  </section>}
  {tab==='catalog'&&<section id="commerce-catalog" aria-labelledby="commerce-tab-catalog"><h2 className="text-lg font-semibold">{t('commerce.catalog_title')}</h2><p className="mt-2 text-sm leading-relaxed text-slate-600">{t('commerce.catalog_help')}</p><div className="mt-4 divide-y divide-slate-100">{catalog.products.map(product=>{const value=state.products[product.id];return <div key={product.id} className="flex items-center gap-3 py-3"><img src={product.image} alt="" width="64" height="64" className="h-16 w-16 shrink-0 rounded-xl object-cover"/><div className="min-w-0 flex-1"><h3 className="text-sm font-semibold">{t(product.nameKey)}</h3><p className="mt-1 text-sm">{price(value.priceCents)}</p><p className="mt-1 text-xs text-slate-500">{value.enabled&&value.stock?t('commerce.stock_left',{count:value.stock}):t('commerce.sold_out')}</p></div><button type="button" aria-label={t('commerce.edit_product',{product:t(product.nameKey)})} className="min-h-11 shrink-0 rounded-full bg-slate-100 px-3 text-xs font-semibold text-slate-700" onClick={event=>{focus.current=event.currentTarget;setEditing(product);}}>{t('common.edit')}</button></div>;})}</div></section>}
  {tab==='cash'&&<section id="commerce-cash" aria-labelledby="commerce-tab-cash"><h2 className="text-lg font-semibold">{t('commerce.cash_title')}</h2><p className="mt-2 text-sm leading-relaxed text-slate-600">{t('commerce.cash_help')}</p>
   <div className="my-4 rounded-2xl bg-slate-50 p-4"><p className="text-sm text-slate-600">{t('commerce.collected_total')}</p><p className="mt-1 text-2xl font-bold">{price(Math.round(done.reduce((sum,order)=>sum+order.total,0)*100))}</p></div>
   {!ready.length&&<div className="my-6"><p className="text-sm text-slate-500">{t('commerce.cash_empty')}</p><Button variant="outline" onClick={()=>setTab('orders')} className="mt-3 h-auto min-h-11 whitespace-normal py-3">{t('commerce.back_orders')}</Button></div>}
   <div className="space-y-3">{ready.map(order=><CommerceOrderCard key={order.id} sector={sector} order={order}><fieldset className="mt-4"><legend className="text-sm font-semibold">{t('commerce.payment')}</legend><div className="mt-2 flex gap-2">{(['cash','card'] as const).map(payment=><label key={payment} className={`flex min-h-11 flex-1 items-center gap-2 rounded-xl border px-3 py-2 text-sm ${(payments[order.id]??'cash')===payment?'border-primary bg-primary/5':'border-slate-200'}`}><input type="radio" name={'payment-'+order.id} checked={(payments[order.id]??'cash')===payment} onChange={()=>setPayments(current=>({...current,[order.id]:payment}))} className="h-4 w-4 accent-primary"/>{t('commerce.'+payment+'_method')}</label>)}</div></fieldset><Button onClick={()=>onCollect(order.id,payments[order.id]??'cash')} className="mt-3 h-auto min-h-11 w-full whitespace-normal py-3">{t('commerce.collected')}</Button></CommerceOrderCard>)}</div>
   <div className="mt-5 space-y-3">{done.map(order=><CommerceOrderCard key={order.id} sector={sector} order={order}/>)}</div>
  </section>}
  <nav aria-label={t('commerce.demo_activity')} className="fixed inset-x-0 bottom-0 z-40 border-t border-slate-100 bg-white/95 px-3 pt-2" style={{paddingBottom:'max(0.5rem, env(safe-area-inset-bottom))'}}><div className="mx-auto grid max-w-3xl grid-cols-3 gap-2">{([{id:'orders',Icon:ClipboardList,count:pending},{id:'catalog',Icon:Package,count:0},{id:'cash',Icon:Wallet,count:ready.length}] as const).map(({id,Icon,count})=><button type="button" id={'commerce-tab-'+id} aria-controls={'commerce-'+id} key={id} aria-pressed={tab===id} onClick={()=>setTab(id)} className={`flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl px-2 py-2 text-xs font-semibold ${tab===id?'bg-primary/10 text-primary':'text-slate-500'}`}><span className="relative"><Icon className="h-5 w-5" aria-hidden="true"/>{count>0&&<span className="absolute -end-3 -top-2 flex min-h-4 min-w-4 items-center justify-center rounded-full bg-primary px-1 text-[10px] text-white">{count}</span>}</span><span>{t('commerce.nav_'+id)}</span></button>)}</div></nav>
  {editing&&<CommerceProductEdit key={editing.id} product={editing} value={state.products[editing.id]} onClose={()=>setEditing(null)} onSave={patch=>onUpdate(editing.id,patch)} returnFocus={focus.current}/>}
 </>;
}
